name: "Execute Tests"
on:
  push:

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python packages
        run: |
          python3 -m pip install -r requirements.txt
      - name: run unit tests
        run: |
          cd app/test/
          python3 -m pytest